name: ci

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    validate-pr:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - run: ./build.cmd Test Pack
