name: release

on:
    workflow_dispatch:

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - run: ./build.cmd Publish CreateGithubRelease
              env:
                  PUBLISH_NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
